# Internal
INTERNAL_UNHANDLED = "INTERNAL_UNHANDLED"

# Request / Validation
REQ_VALIDATION_FAILED = "REQ_VALIDATION_FAILED"
REQ_UNSUPPORTED_MEDIA_TYPE = "REQ_UNSUPPORTED_MEDIA_TYPE"
REQ_EMPTY_IMAGE_BYTES = "REQ_EMPTY_IMAGE_BYTES"
REQ_IMAGE_BYTES_TOO_SMALL = "REQ_IMAGE_BYTES_TOO_SMALL"

# Upstream (Vision)
UPSTREAM_VISION_TIMEOUT = "UPSTREAM_VISION_TIMEOUT"
UPSTREAM_VISION_FAILED = "UPSTREAM_VISION_FAILED"

# Analysis (OpenCV / pipeline)
ANALYSIS_INVALID_RESULT = "ANALYSIS_INVALID_RESULT"
ANALYSIS_OPENCV_FAILED = "ANALYSIS_OPENCV_FAILED"
ANALYSIS_NO_VALID_CANDIDATE = "ANALYSIS_NO_VALID_CANDIDATE"
